### ISSUE TITLE
How to train/generate correctly sentencepiece source and target models to use them as "sp_source_model" and "sp_target_model"

### ISSUE THREAD

**Issue by ican24** [ymoslem/CTranslate-NMT-Web-Interface#1]
Dear Yasmin,

Thank you for your great job!
Could you show any link or example how to train/generate correctly sentencepiece source and target models to use them as "sp_source_model" and "sp_target_model" ?
```
...
sp_source_model = "/path/to/the/sentencepiece/source/model/file"
sp_target_model = "/path/to/the/sentencepiece/target/model/file"
...

```
I had trained translation model (500k) for Armenian-English languages by OpenNMT-tf default settings 
`onmt-main --model_type Transformer --config conf/datahyen.yml --auto_config train --with_eval
`
I tried many option of spm_train, but without any succes.
Unfortunately there is a few information in Internet about sentencepiece model training/generation for my case. 
As the example (wmtende) it uses share model & vocabulary.

Thank you in advance!

**Comment by ymoslem** [comment]
Hi Artak!

You can use [SentencePiece](https://github.com/google/sentencepiece) to train sub-wording models. You can refer to their documentation and/or use these [scripts](https://github.com/ymoslem/MT-Preparation) after editing them for your needs.

For questions about OpenNMT-tf, please refer to their [forum](https://forum.opennmt.net/), which already has many posts that can help as well.

All the best,
Yasmin

**Comment by ican24** [comment]
Hi Yasmin,

It is not useful. 
Recently I tried all your mentioned  SentencePiece methods and tricks in the OpenNMT forum to force my generated OpenNMT-tf translation model to work with your CTranslate-NMT-Web-Interface.
Anyway thank you
I'll try to find solution for my case myself.

**Comment by ymoslem** [comment]
CTranslate does not require SentencePiece. If you trained your OpenNMT-tf model without SentencePiece, you should remove any SentencePiece lines from your interface.

SentencePiece is one method of tokenization you use to process your data **before** training your model. If you used another method of tokenization, use the same method to process your data before translation.

**Comment by ican24** [comment]
Thank you very much!
I removed SentencePiece lines from my code and everything started working. 
Good luck in your development!
