### ISSUE TITLE
download ct_model, sp_source_model, and sp_target_model files?

### ISSUE THREAD

**Issue by steamboatid** [ymoslem/CTranslate-NMT-Web-Interface#2]
hi,

how to download those files?
i've been brwose around and cant find the urls of those models?
is there any way to get the complete lists of the model files?

thanks.

**Comment by ymoslem** [comment]
Hello! The paths suggest you have your own models. As an example, you can download and use the model [here](https://github.com/ymoslem/DesktopTranslator/releases/download/v0.2.1/opus-eng-fra-ct2.zip). Note that the SentencePiece model used shared vocabulary, so you can use it for both the source and target. All the best!

**Comment by steamboatid** [comment]
thank you for the reply.
maybe i will try with desktop translator first
